### ISSUE TITLE
Checklist for Version 0.8.4

### ISSUE THREAD

**Issue by SamBrishes** [SamBrishes/FoxCMS#3]
Hello,

the following checklist shows the progress of the first Alpha Version of the Fox CMS 0.8.4 (Please Note: The develop branch doesn't offer a stable / full release, it's just the current work in progress!). 

The list below doesn't show every change, check out the CHANGELOG.md file within the develop branch to see all (or at least "almost all") changes. Fox CMS Version 0.8.4 also doesn't contain "really big" changes compared to the Wolf CMS!

- [ ]   Update BasixFox theme.
- [ ]   Update Simple theme.
- [ ]   Update Email helper class.
- [ ]   Update Form helper class.
- [ ]   Update Gravatar helper class.
- [ ]   Update Pagination helper class.
- [ ]   Update Upload helper class.
- [ ]   Update all plugins.

## Finished
- [x]   Add new security features (SecureToken, `password_hash()`, ...)
- [x]   Create Install / Migration Wizard
- [x]   Split Framework classes in single files
- [x]   Update files to the new coding style
- [x]   Update BigInteger helper class
- [x]   Update Hash helper class (Marked as deprecated!)
- [x]   Update Kses helper class
- [x]   Update Validate helper class
- [x]   Update ZIP helper class
- [x]   Fix known XSS Vulnerabilities / Errors

Sincerly,<br />
Sam.

**Comment by Wemago** [comment]
Is your fork death also?
Would be interested to follow up a frog/wolf evolution.

**Comment by SamBrishes** [comment]
Hellow,

The fork was "paused" for a long time, since I had some private issues and I also focused on other systems and projects.

However, I started to work on Fox CMS again, but it will definitely take time before 0.8.4 gets published, because I want to port the whole script to PHP 7.2.0 due to a better workflow. So I cannot guarantee anything at the moment, sorry.

Sincerely,
Sam.

**Comment by Wemago** [comment]
Hi Sam, Any news?

**Comment by vintzl** [comment]
@SamBrishes 

How could we help?

Do you accept Pull Requests?

Do you have a definite TODO list?
